import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { identityFetch } from "@/lib/identity-api";
import { useAuth } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/settings/email")({ component: EmailSettingsPage });

function EmailSettingsPage() {
  const { session } = useAuth();
  const [provider, setProvider] = useState("Resend"); const [fromEmail, setFromEmail] = useState(""); const [fromDisplayName, setFromDisplayName] = useState(""); const [resendApiKey, setResendApiKey] = useState(""); const [sesRegion, setSesRegion] = useState(""); const [sesAccessKey, setSesAccessKey] = useState(""); const [sesSecretKey, setSesSecretKey] = useState(""); const [sesConfigurationSetName, setSesConfigurationSetName] = useState(""); const [host, setHost] = useState(""); const [port, setPort] = useState("587"); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [passwordResetTemplate, setPasswordResetTemplate] = useState("identity-password-reset"); const [emailVerificationTemplate, setEmailVerificationTemplate] = useState("identity-email-verification");
  const [keySuffix, setKeySuffix] = useState<string | null>(null);
  useEffect(() => { if (!session) return; identityFetch<{ configured: boolean; provider?: string; fromEmail?: string; fromDisplayName?: string; passwordResetTemplate?: string; emailVerificationTemplate?: string; resendApiKeySuffix?: string | null }>(session, "/api/admin/tenant/smtp").then((x) => { if (!x.configured) return; setProvider(x.provider ?? "Resend"); setFromEmail(x.fromEmail ?? ""); setFromDisplayName(x.fromDisplayName ?? ""); setPasswordResetTemplate(x.passwordResetTemplate ?? "identity-password-reset"); setEmailVerificationTemplate(x.emailVerificationTemplate ?? "identity-email-verification"); setKeySuffix(x.resendApiKeySuffix ?? null); }).catch(() => toast.error("Could not load email settings")); }, [session]);
  const save = async () => { try { await identityFetch(session, "/api/admin/tenant/smtp", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, host, port: Number(port), username, password, useTls: true, fromEmail, fromDisplayName, resendApiKey: provider === "Resend" ? resendApiKey : undefined, sesRegion, sesAccessKey, sesSecretKey, sesConfigurationSetName, passwordResetTemplate, emailVerificationTemplate }) }); toast.success("Email settings saved"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save email settings"); } };
  return <main className="space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Email delivery</h1><p className="text-muted-foreground">Configure the active provider and templates for this tenant.</p></div><div className="grid max-w-2xl gap-4 rounded-lg border p-5"><div><Label>Provider</Label><select value={provider} onChange={(e) => setProvider(e.target.value)} className="mt-1 h-10 w-full rounded-md border bg-background px-3"><option>Resend</option><option>Smtp</option><option>Ses</option></select></div><div><Label>From email</Label><Input value={fromEmail} onChange={(e) => setFromEmail(e.target.value)} /></div><div><Label>From display name</Label><Input value={fromDisplayName} onChange={(e) => setFromDisplayName(e.target.value)} /></div>{provider === "Resend" && <div><Label>Resend API key {keySuffix && <span className="text-muted-foreground">({keySuffix})</span>}</Label><Input type="password" value={resendApiKey} onChange={(e) => setResendApiKey(e.target.value)} placeholder={keySuffix ? "Leave blank to keep current key" : "re_..."} /></div>}{provider === "Ses" && <><div><Label>AWS region</Label><Input value={sesRegion} onChange={(e) => setSesRegion(e.target.value)} placeholder="ap-southeast-1" /></div><div><Label>Access key ID</Label><Input type="password" value={sesAccessKey} onChange={(e) => setSesAccessKey(e.target.value)} /></div><div><Label>Secret access key</Label><Input type="password" value={sesSecretKey} onChange={(e) => setSesSecretKey(e.target.value)} /></div><div><Label>Configuration set (optional)</Label><Input value={sesConfigurationSetName} onChange={(e) => setSesConfigurationSetName(e.target.value)} /></div></>}{provider === "Smtp" && <><div><Label>Host</Label><Input value={host} onChange={(e) => setHost(e.target.value)} /></div><div><Label>Port</Label><Input value={port} onChange={(e) => setPort(e.target.value)} /></div><div><Label>Username</Label><Input value={username} onChange={(e) => setUsername(e.target.value)} /></div><div><Label>Password</Label><Input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></div></>}<div><Label>Password reset template ID / alias</Label><Input value={passwordResetTemplate} onChange={(e) => setPasswordResetTemplate(e.target.value)} /></div><div><Label>Email verification template ID / alias</Label><Input value={emailVerificationTemplate} onChange={(e) => setEmailVerificationTemplate(e.target.value)} /></div><Button onClick={save}>Save settings</Button></div></main>;
}
